version: '3.8'

services:

  ollama:
    image: ollama/ollama:latest
    volumes:
      - /home/daniel/ClusterStorage/data/ollama:/root/.ollama
    networks:
      - jarvis-net
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == daniel-B450M-H
      resources:
        limits:
          memory: 12G
        reservations:
          memory: 4G
      restart_policy:
        condition: on-failure

  webui:
    image: ghcr.io/open-webui/open-webui:main
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_NAME=Jarvis
    volumes:
      - /home/daniel/ClusterStorage/data/webui:/app/backend/data
    ports:
      - "3000:8080"
    networks:
      - jarvis-net
    depends_on:
      - ollama
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == daniel-B450M-H
      restart_policy:
        condition: on-failure

networks:
  jarvis-net:
    external: true
